# ========================================
# CONFIGURACIÓN GENERAL
# ========================================
spring.application.name=rydex
server.port=8080

# ========================================
# PRODUCCIÓN CON MYSQL (AIVEN EN LA NUBE)
# ========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# ========================================
# JPA / HIBERNATE
# ========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# JWT
# ========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ========================================
# CLOUDINARY (FOTOS EN LA NUBE)
# ========================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ====================== H2 LOCAL DATABASE ===============================