# ========================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ========================================
spring.application.name=rydex

# ========================================
# CONFIGURACIÓN DEL SERVIDOR
# ========================================
server.port=8080

# ========================================
# CONFIGURACIÓN DE BASE DE DATOS (H2)
# ========================================
spring.datasource.url=jdbc:h2:mem:rydex_db

#Credenciales de acceso por defecto
spring.datasource.username=sa
spring.datasource.password=

# Configurar el Driver (puente entre Java y la DB)
spring.datasource.driver-class-name=org.h2.Driver

# Dialecto que Hibernate usa para generar SQL compatible con H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ========================================
# Estrategia de creación de tablas
# create-drop = crea al iniciar y borra al apagar
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear el SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# HERRAMIENTAS DE DESARROLLO (H2 CONSOLE)
# ========================================

# Habilitar consola web de H2
spring.h2.console.enabled=true

# Ruta donde se accede a la consola
spring.h2.console.path=/h2-console